### ISSUE TITLE
Netlify Website Not Working

### ISSUE THREAD

**Issue by verajpatel** [verajpatel/ecommerce-pattern-library#11]
@thomasjbradley

There are problems with my pattern library Netlify link, mainly the images in the pattern library not loading, and the website url not physically loading the website, only giving an error.

**Comment by thomasjbradley** [comment]
What’s the error that you’re seeing?

**Comment by thomasjbradley** [comment]
Errors in your Terminal still?
Errors in the Netlify Deploys panel?

**Comment by verajpatel** [comment]
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/43155563/79516658-fae3eb00-8019-11ea-836b-8acf2dc49d73.png">
There are errors in the Terminal still, yes, plus, when I remove the pattern library tag, all it shows on the website is this.

**Comment by thomasjbradley** [comment]
Terminal error fixes:

1. https://github.com/verajpatel/ecommerce-pattern-library/blob/master/_patterns/cards/config.yml#L8
Unindent this line so it aligns with `name`

2. Highlight all this & press `Shift-Tab`:
https://github.com/verajpatel/ecommerce-pattern-library/blob/master/_patterns/header/config.yml#L11-L34
It all needs to be unindented a step.

3. https://github.com/verajpatel/ecommerce-pattern-library/blob/master/index.html#L8
This line refers to a pattern that doesn’t exist in your `banners` pattern folder.

**Comment by verajpatel** [comment]
What about entering the physical website itself? There's something wrong with the link and I don't know what the problem is.

**Comment by thomasjbradley** [comment]
It will not build until all the problems in the website are fixed. When everything in Terminal is fixed & it’s working properly, then the live website on Netlify should also start working.
