### ISSUE TITLE
More grades for certain parts

### ISSUE THREAD

**Issue by verajpatel** [verajpatel/ecommerce-pattern-library#2]
Could you enter grades for the following parts:

Week 6: Informal accessibility testing.
Week 9: Showing codes with layouts, Building pages with patterns, The leftovers
Week 10: Preparing product data, Jekyll generators.
Week 11: Finalizing product docs.

@thomasjbradley

**Comment by thomasjbradley** [comment]
What changes did you make to your website for "The Leftovers"?

**Comment by thomasjbradley** [comment]
For "Sharing code with layouts" I don’t see the `index.html` or the `products.html` files.

**Comment by verajpatel** [comment]
The index.html and products.html files are located in _layouts.

**Comment by thomasjbradley** [comment]
`index.html` needs to be moved to the root folder.

Duplicate the `products.html` file—there needs to be one in the root folder & another inside `_layouts`

`/_layouts/product.html` — first remove the “s” from the filename
Then it should only have this code:
https://github.com/verajpatel/ecommerce-pattern-library/blob/master/_layouts/products.html#L1-L10

`/products.html` — should only have this code—along with the `layout: default` stuff at the top.
https://github.com/verajpatel/ecommerce-pattern-library/blob/master/_layouts/products.html#L12-L30
