### ISSUE TITLE
Netlify & Images

### ISSUE THREAD

**Issue by verajpatel** [verajpatel/ecommerce-pattern-library#3]
Images won't load for my Netlify website. The link is down below.
https://thirsty-shockley-543bcd.netlify.com/pattern-library/#brand

@thomasjbradley

**Comment by thomasjbradley** [comment]
The whole thing seems to be broken. Are you seeing errors in Terminal on your computer?

**Comment by verajpatel** [comment]
I have been, yes.

**Comment by thomasjbradley** [comment]
Send me a screenshot of the Terminal errors.

**Comment by verajpatel** [comment]
<img width="1429" alt="Screen Shot 2020-04-07 at 7 40 32 PM" src="https://user-images.githubusercontent.com/43155563/78729285-b1075080-7907-11ea-8cb0-b06d8ac8e72b.png">

**Comment by thomasjbradley** [comment]
On this line here, there’s an extra `"` quotemark that needs to be deleted:
https://github.com/verajpatel/ecommerce-pattern-library/blob/master/_patterns/banners/banner.html#L6
